[[rust-analyzer.assist.expressionFillDefault]]rust-analyzer.assist.expressionFillDefault (default: `"todo"`)::
+
--
Placeholder expression to use for missing expressions in assists.
--
[[rust-analyzer.cargo.autoreload]]rust-analyzer.cargo.autoreload (default: `true`)::
+
--
Automatically refresh project info via `cargo metadata` on
`Cargo.toml` or `.cargo/config.toml` changes.
--
[[rust-analyzer.cargo.buildScripts.enabled]]rust-analyzer.cargo.buildScripts.enabled (default: `true`)::
+
--
Run build scripts (`build.rs`) for more precise code analysis.
--
[[rust-analyzer.cargo.buildScripts.overrideCommand]]rust-analyzer.cargo.buildScripts.overrideCommand (default: `null`)::
+
--
Override the command rust-analyzer uses to run build scripts and
build procedural macros. The command is required to output json
and should therefor include `--message-format=json` or a similar
option.

By default, a cargo invocation will be constructed for the configured
targets and features, with the following base command line:

```bash
cargo check --quiet --workspace --message-format=json --all-targets
```
.
--
[[rust-analyzer.cargo.buildScripts.useRustcWrapper]]rust-analyzer.cargo.buildScripts.useRustcWrapper (default: `true`)::
+
--
Use `RUSTC_WRAPPER=rust-analyzer` when running build scripts to
avoid compiling unnecessary things.
--
[[rust-analyzer.cargo.features]]rust-analyzer.cargo.features (default: `[]`)::
+
--
List of features to activate.

Set this to `"all"` to pass `--all-features` to cargo.
--
[[rust-analyzer.cargo.noDefaultFeatures]]rust-analyzer.cargo.noDefaultFeatures (default: `false`)::
+
--
Whether to pass `--no-default-features` to cargo.
--
[[rust-analyzer.cargo.noSysroot]]rust-analyzer.cargo.noSysroot (default: `false`)::
+
--
Internal config for debugging, disables loading of sysroot crates.
--
[[rust-analyzer.cargo.target]]rust-analyzer.cargo.target (default: `null`)::
+
--
Compilation target override (target triple).
--
[[rust-analyzer.cargo.unsetTest]]rust-analyzer.cargo.unsetTest (default: `["core"]`)::
+
--
Unsets `#[cfg(test)]` for the specified crates.
--
[[rust-analyzer.checkOnSave.allTargets]]rust-analyzer.checkOnSave.allTargets (default: `true`)::
+
--
Check all targets and tests (`--all-targets`).
--
[[rust-analyzer.checkOnSave.command]]rust-analyzer.checkOnSave.command (default: `"check"`)::
+
--
Cargo command to use for `cargo check`.
--
[[rust-analyzer.checkOnSave.enabled]]rust-analyzer.checkOnSave.enabled (default: `true`)::
+
--
Run specified `cargo check` command for diagnostics on save.
--
[[rust-analyzer.checkOnSave.extraArgs]]rust-analyzer.checkOnSave.extraArgs (default: `[]`)::
+
--
Extra arguments for `cargo check`.
--
[[rust-analyzer.checkOnSave.features]]rust-analyzer.checkOnSave.features (default: `null`)::
+
--
List of features to activate. Defaults to
`#rust-analyzer.cargo.features#`.

Set to `"all"` to pass `--all-features` to cargo.
--
[[rust-analyzer.checkOnSave.noDefaultFeatures]]rust-analyzer.checkOnSave.noDefaultFeatures (default: `null`)::
+
--
Do not activate the `default` feature.
--
[[rust-analyzer.checkOnSave.overrideCommand]]rust-analyzer.checkOnSave.overrideCommand (default: `null`)::
+
--
Override the command rust-analyzer uses to  run build scripts and
build procedural macros. The command is required to output json
and should therefor include `--message-format=json` or a similar
option.

An example command would be:

```bash
cargo check --workspace --message-format=json --all-targets
```
.
--
[[rust-analyzer.checkOnSave.target]]rust-analyzer.checkOnSave.target (default: `null`)::
+
--
Check for a specific target. Defaults to
`#rust-analyzer.cargo.target#`.
--
[[rust-analyzer.completion.autoimport.enabled]]rust-analyzer.completion.autoimport.enabled (default: `true`)::
+
--
Toggles the additional completions that automatically add imports when completed.
Note that your client must specify the `additionalTextEdits` LSP client capability to truly have this feature enabled.
--
[[rust-analyzer.completion.autoself.enabled]]rust-analyzer.completion.autoself.enabled (default: `true`)::
+
--
Toggles the additional completions that automatically show method calls and field accesses
with `self` prefixed to them when inside a method.
--
[[rust-analyzer.completion.callable.snippets]]rust-analyzer.completion.callable.snippets (default: `"fill_arguments"`)::
+
--
Whether to add parenthesis and argument snippets when completing function.
--
[[rust-analyzer.completion.postfix.enabled]]rust-analyzer.completion.postfix.enabled (default: `true`)::
+
--
Whether to show postfix snippets like `dbg`, `if`, `not`, etc.
--
[[rust-analyzer.completion.privateEditable.enabled]]rust-analyzer.completion.privateEditable.enabled (default: `false`)::
+
--
Enables completions of private items and fields that are defined in the current workspace even if they are not visible at the current position.
--
[[rust-analyzer.completion.snippets.custom]]rust-analyzer.completion.snippets.custom::
+
--
Default:
----
{
            "Arc::new": {
                "postfix": "arc",
                "body": "Arc::new(${receiver})",
                "requires": "std::sync::Arc",
                "description": "Put the expression into an `Arc`",
                "scope": "expr"
            },
            "Rc::new": {
                "postfix": "rc",
                "body": "Rc::new(${receiver})",
                "requires": "std::rc::Rc",
                "description": "Put the expression into an `Rc`",
                "scope": "expr"
            },
            "Box::pin": {
                "postfix": "pinbox",
                "body": "Box::pin(${receiver})",
                "requires": "std::boxed::Box",
                "description": "Put the expression into a pinned `Box`",
                "scope": "expr"
            },
            "Ok": {
                "postfix": "ok",
                "body": "Ok(${receiver})",
                "description": "Wrap the expression in a `Result::Ok`",
                "scope": "expr"
            },
            "Err": {
                "postfix": "err",
                "body": "Err(${receiver})",
                "description": "Wrap the expression in a `Result::Err`",
                "scope": "expr"
            },
            "Some": {
                "postfix": "some",
                "body": "Some(${receiver})",
                "description": "Wrap the expression in an `Option::Some`",
                "scope": "expr"
            }
        }
----
Custom completion snippets.

--
[[rust-analyzer.diagnostics.disabled]]rust-analyzer.diagnostics.disabled (default: `[]`)::
+
--
List of rust-analyzer diagnostics to disable.
--
[[rust-analyzer.diagnostics.enabled]]rust-analyzer.diagnostics.enabled (default: `true`)::
+
--
Whether to show native rust-analyzer diagnostics.
--
[[rust-analyzer.diagnostics.experimental.enabled]]rust-analyzer.diagnostics.experimental.enabled (default: `false`)::
+
--
Whether to show experimental rust-analyzer diagnostics that might
have more false positives than usual.
--
[[rust-analyzer.diagnostics.remapPrefix]]rust-analyzer.diagnostics.remapPrefix (default: `{}`)::
+
--
Map of prefixes to be substituted when parsing diagnostic file paths.
This should be the reverse mapping of what is passed to `rustc` as `--remap-path-prefix`.
--
[[rust-analyzer.diagnostics.warningsAsHint]]rust-analyzer.diagnostics.warningsAsHint (default: `[]`)::
+
--
List of warnings that should be displayed with hint severity.

The warnings will be indicated by faded text or three dots in code
and will not show up in the `Problems Panel`.
--
[[rust-analyzer.diagnostics.warningsAsInfo]]rust-analyzer.diagnostics.warningsAsInfo (default: `[]`)::
+
--
List of warnings that should be displayed with info severity.

The warnings will be indicated by a blue squiggly underline in code
and a blue icon in the `Problems Panel`.
--
[[rust-analyzer.files.excludeDirs]]rust-analyzer.files.excludeDirs (default: `[]`)::
+
--
These directories will be ignored by rust-analyzer. They are
relative to the workspace root, and globs are not supported. You may
also need to add the folders to Code's `files.watcherExclude`.
--
[[rust-analyzer.files.watcher]]rust-analyzer.files.watcher (default: `"client"`)::
+
--
Controls file watching implementation.
--
[[rust-analyzer.highlightRelated.breakPoints.enabled]]rust-analyzer.highlightRelated.breakPoints.enabled (default: `true`)::
+
--
Enables highlighting of related references while the cursor is on `break`, `loop`, `while`, or `for` keywords.
--
[[rust-analyzer.highlightRelated.exitPoints.enabled]]rust-analyzer.highlightRelated.exitPoints.enabled (default: `true`)::
+
--
Enables highlighting of all exit points while the cursor is on any `return`, `?`, `fn`, or return type arrow (`->`).
--
[[rust-analyzer.highlightRelated.references.enabled]]rust-analyzer.highlightRelated.references.enabled (default: `true`)::
+
--
Enables highlighting of related references while the cursor is on any identifier.
--
[[rust-analyzer.highlightRelated.yieldPoints.enabled]]rust-analyzer.highlightRelated.yieldPoints.enabled (default: `true`)::
+
--
Enables highlighting of all break points for a loop or block context while the cursor is on any `async` or `await` keywords.
--
[[rust-analyzer.hover.actions.debug.enabled]]rust-analyzer.hover.actions.debug.enabled (default: `true`)::
+
--
Whether to show `Debug` action. Only applies when
`#rust-analyzer.hoverActions.enable#` is set.
--
[[rust-analyzer.hover.actions.enabled]]rust-analyzer.hover.actions.enabled (default: `true`)::
+
--
Whether to show HoverActions in Rust files.
--
[[rust-analyzer.hover.actions.gotoTypeDef.enabled]]rust-analyzer.hover.actions.gotoTypeDef.enabled (default: `true`)::
+
--
Whether to show `Go to Type Definition` action. Only applies when
`#rust-analyzer.hoverActions.enable#` is set.
--
[[rust-analyzer.hover.actions.implementations.enabled]]rust-analyzer.hover.actions.implementations.enabled (default: `true`)::
+
--
Whether to show `Implementations` action. Only applies when
`#rust-analyzer.hoverActions.enable#` is set.
--
[[rust-analyzer.hover.actions.references.enabled]]rust-analyzer.hover.actions.references.enabled (default: `false`)::
+
--
Whether to show `References` action. Only applies when
`#rust-analyzer.hoverActions.enable#` is set.
--
[[rust-analyzer.hover.actions.run.enabled]]rust-analyzer.hover.actions.run.enabled (default: `true`)::
+
--
Whether to show `Run` action. Only applies when
`#rust-analyzer.hoverActions.enable#` is set.
--
[[rust-analyzer.hover.documentation.enabled]]rust-analyzer.hover.documentation.enabled (default: `true`)::
+
--
Whether to show documentation on hover.
--
[[rust-analyzer.hover.links.enabled]]rust-analyzer.hover.links.enabled (default: `true`)::
+
--
Use markdown syntax for links in hover.
--
[[rust-analyzer.imports.granularity.enforce]]rust-analyzer.imports.granularity.enforce (default: `false`)::
+
--
Whether to enforce the import granularity setting for all files. If set to false rust-analyzer will try to keep import styles consistent per file.
--
[[rust-analyzer.imports.granularity.group]]rust-analyzer.imports.granularity.group (default: `"crate"`)::
+
--
How imports should be grouped into use statements.
--
[[rust-analyzer.imports.group.enabled]]rust-analyzer.imports.group.enabled (default: `true`)::
+
--
Group inserted imports by the https://rust-analyzer.github.io/manual.html#auto-import[following order]. Groups are separated by newlines.
--
[[rust-analyzer.imports.merge.glob]]rust-analyzer.imports.merge.glob (default: `true`)::
+
--
Whether to allow import insertion to merge new imports into single path glob imports like `use std::fmt::*;`.
--
[[rust-analyzer.imports.prefix]]rust-analyzer.imports.prefix (default: `"plain"`)::
+
--
The path structure for newly inserted paths to use.
--
[[rust-analyzer.inlayHints.chainingHints.enabled]]rust-analyzer.inlayHints.chainingHints.enabled (default: `true`)::
+
--
Whether to show inlay type hints for method chains.
--
[[rust-analyzer.inlayHints.closureReturnTypeHints.enabled]]rust-analyzer.inlayHints.closureReturnTypeHints.enabled (default: `false`)::
+
--
Whether to show inlay type hints for return types of closures with blocks.
--
[[rust-analyzer.inlayHints.lifetimeElisionHints.enabled]]rust-analyzer.inlayHints.lifetimeElisionHints.enabled (default: `"never"`)::
+
--
Whether to show inlay type hints for elided lifetimes in function signatures.
--
[[rust-analyzer.inlayHints.lifetimeElisionHints.useParameterNames]]rust-analyzer.inlayHints.lifetimeElisionHints.useParameterNames (default: `false`)::
+
--
Whether to prefer using parameter names as the name for elided lifetime hints if possible.
--
[[rust-analyzer.inlayHints.maxLength]]rust-analyzer.inlayHints.maxLength (default: `25`)::
+
--
Maximum length for inlay hints. Set to null to have an unlimited length.
--
[[rust-analyzer.inlayHints.parameterHints.enabled]]rust-analyzer.inlayHints.parameterHints.enabled (default: `true`)::
+
--
Whether to show function parameter name inlay hints at the call
site.
--
[[rust-analyzer.inlayHints.reborrowHints.enabled]]rust-analyzer.inlayHints.reborrowHints.enabled (default: `false`)::
+
--
Whether to show inlay type hints for compiler inserted reborrows.
--
[[rust-analyzer.inlayHints.renderColons]]rust-analyzer.inlayHints.renderColons (default: `true`)::
+
--
Whether to render leading colons for type hints, and trailing colons for parameter hints.
--
[[rust-analyzer.inlayHints.typeHints.enabled]]rust-analyzer.inlayHints.typeHints.enabled (default: `true`)::
+
--
Whether to show inlay type hints for variables.
--
[[rust-analyzer.inlayHints.typeHints.hideNamedConstructor]]rust-analyzer.inlayHints.typeHints.hideNamedConstructor (default: `false`)::
+
--
Whether to hide inlay type hints for constructors.
--
[[rust-analyzer.joinLines.joinAssignments]]rust-analyzer.joinLines.joinAssignments (default: `true`)::
+
--
Join lines merges consecutive declaration and initialization of an assignment.
--
[[rust-analyzer.joinLines.joinElseIf]]rust-analyzer.joinLines.joinElseIf (default: `true`)::
+
--
Join lines inserts else between consecutive ifs.
--
[[rust-analyzer.joinLines.removeTrailingComma]]rust-analyzer.joinLines.removeTrailingComma (default: `true`)::
+
--
Join lines removes trailing commas.
--
[[rust-analyzer.joinLines.unwrapTrivialBlock]]rust-analyzer.joinLines.unwrapTrivialBlock (default: `true`)::
+
--
Join lines unwraps trivial blocks.
--
[[rust-analyzer.lens.debug.enabled]]rust-analyzer.lens.debug.enabled (default: `true`)::
+
--
Whether to show `Debug` lens. Only applies when
`#rust-analyzer.lens.enable#` is set.
--
[[rust-analyzer.lens.enabled]]rust-analyzer.lens.enabled (default: `true`)::
+
--
Whether to show CodeLens in Rust files.
--
[[rust-analyzer.lens.forceCustomCommands]]rust-analyzer.lens.forceCustomCommands (default: `true`)::
+
--
Internal config: use custom client-side commands even when the
client doesn't set the corresponding capability.
--
[[rust-analyzer.lens.implementations.enabled]]rust-analyzer.lens.implementations.enabled (default: `true`)::
+
--
Whether to show `Implementations` lens. Only applies when
`#rust-analyzer.lens.enable#` is set.
--
[[rust-analyzer.lens.references.adt.enabled]]rust-analyzer.lens.references.adt.enabled (default: `false`)::
+
--
Whether to show `References` lens for Struct, Enum, and Union.
Only applies when `#rust-analyzer.lens.enable#` is set.
--
[[rust-analyzer.lens.references.enumVariant.enabled]]rust-analyzer.lens.references.enumVariant.enabled (default: `false`)::
+
--
Whether to show `References` lens for Enum Variants.
Only applies when `#rust-analyzer.lens.enable#` is set.
--
[[rust-analyzer.lens.references.method.enabled]]rust-analyzer.lens.references.method.enabled (default: `false`)::
+
--
Whether to show `Method References` lens. Only applies when
`#rust-analyzer.lens.enable#` is set.
--
[[rust-analyzer.lens.references.trait.enabled]]rust-analyzer.lens.references.trait.enabled (default: `false`)::
+
--
Whether to show `References` lens for Trait.
Only applies when `#rust-analyzer.lens.enable#` is set.
--
[[rust-analyzer.lens.run.enabled]]rust-analyzer.lens.run.enabled (default: `true`)::
+
--
Whether to show `Run` lens. Only applies when
`#rust-analyzer.lens.enable#` is set.
--
[[rust-analyzer.linkedProjects]]rust-analyzer.linkedProjects (default: `[]`)::
+
--
Disable project auto-discovery in favor of explicitly specified set
of projects.

Elements must be paths pointing to `Cargo.toml`,
`rust-project.json`, or JSON objects in `rust-project.json` format.
--
[[rust-analyzer.lru.capacity]]rust-analyzer.lru.capacity (default: `null`)::
+
--
Number of syntax trees rust-analyzer keeps in memory. Defaults to 128.
--
[[rust-analyzer.notifications.cargoTomlNotFound]]rust-analyzer.notifications.cargoTomlNotFound (default: `true`)::
+
--
Whether to show `can't find Cargo.toml` error message.
--
[[rust-analyzer.primeCaches.enabled]]rust-analyzer.primeCaches.enabled (default: `true`)::
+
--
Warm up caches on project load.
--
[[rust-analyzer.primeCaches.numThreads]]rust-analyzer.primeCaches.numThreads (default: `0`)::
+
--
How many worker threads to to handle priming caches. The default `0` means to pick automatically.
--
[[rust-analyzer.procMacro.attributes.enabled]]rust-analyzer.procMacro.attributes.enabled (default: `true`)::
+
--
Expand attribute macros. Requires `#rust-analyzer.procMacro.enable#` to be set.
--
[[rust-analyzer.procMacro.enabled]]rust-analyzer.procMacro.enabled (default: `true`)::
+
--
Enable support for procedural macros, implies `#rust-analyzer.cargo.buildScripts.enable#`.
--
[[rust-analyzer.procMacro.ignored]]rust-analyzer.procMacro.ignored (default: `{}`)::
+
--
These proc-macros will be ignored when trying to expand them.

This config takes a map of crate names with the exported proc-macro names to ignore as values.
--
[[rust-analyzer.procMacro.server]]rust-analyzer.procMacro.server (default: `null`)::
+
--
Internal config, path to proc-macro server executable (typically,
this is rust-analyzer itself, but we override this in tests).
--
[[rust-analyzer.runnables.command]]rust-analyzer.runnables.command (default: `null`)::
+
--
Command to be executed instead of 'cargo' for runnables.
--
[[rust-analyzer.runnables.extraArgs]]rust-analyzer.runnables.extraArgs (default: `[]`)::
+
--
Additional arguments to be passed to cargo for runnables such as
tests or binaries. For example, it may be `--release`.
--
[[rust-analyzer.rustc.source]]rust-analyzer.rustc.source (default: `null`)::
+
--
Path to the Cargo.toml of the rust compiler workspace, for usage in rustc_private
projects, or "discover" to try to automatically find it if the `rustc-dev` component
is installed.

Any project which uses rust-analyzer with the rustcPrivate
crates must set `[package.metadata.rust-analyzer] rustc_private=true` to use it.

This option does not take effect until rust-analyzer is restarted.
--
[[rust-analyzer.rustfmt.extraArgs]]rust-analyzer.rustfmt.extraArgs (default: `[]`)::
+
--
Additional arguments to `rustfmt`.
--
[[rust-analyzer.rustfmt.overrideCommand]]rust-analyzer.rustfmt.overrideCommand (default: `null`)::
+
--
Advanced option, fully override the command rust-analyzer uses for
formatting.
--
[[rust-analyzer.rustfmt.rangeFormatting.enabled]]rust-analyzer.rustfmt.rangeFormatting.enabled (default: `false`)::
+
--
Enables the use of rustfmt's unstable range formatting command for the
`textDocument/rangeFormatting` request. The rustfmt option is unstable and only
available on a nightly build.
--
[[rust-analyzer.semanticHighlighting.strings.enabled]]rust-analyzer.semanticHighlighting.strings.enabled (default: `true`)::
+
--
Use semantic tokens for strings.

In some editors (e.g. vscode) semantic tokens override other highlighting grammars.
By disabling semantic tokens for strings, other grammars can be used to highlight
their contents.
--
[[rust-analyzer.signatureInfo.detail]]rust-analyzer.signatureInfo.detail (default: `"full"`)::
+
--
Show full signature of the callable. Only shows parameters if disabled.
--
[[rust-analyzer.signatureInfo.documentation.enabled]]rust-analyzer.signatureInfo.documentation.enabled (default: `true`)::
+
--
Show documentation.
--
[[rust-analyzer.workspace.symbol.search.kind]]rust-analyzer.workspace.symbol.search.kind (default: `"only_types"`)::
+
--
Workspace symbol search kind.
--
[[rust-analyzer.workspace.symbol.search.limit]]rust-analyzer.workspace.symbol.search.limit (default: `128`)::
+
--
Limits the number of items returned from a workspace symbol search (Defaults to 128).
Some clients like vs-code issue new searches on result filtering and don't require all results to be returned in the initial search.
Other clients requires all results upfront and might require a higher limit.
--
[[rust-analyzer.workspace.symbol.search.scope]]rust-analyzer.workspace.symbol.search.scope (default: `"workspace"`)::
+
--
Workspace symbol search scope.
--
