[package]
name = "proc-macro-api"
version = "0.0.0"
repository.workspace = true
description = "RPC Api for the `proc-macro-srv` crate of rust-analyzer."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
serde.workspace = true
serde_derive.workspace = true
serde_json = { workspace = true, features = ["unbounded_depth"] }
tracing.workspace = true
rustc-hash.workspace = true
indexmap.workspace = true

# local deps
paths = { workspace = true, features = ["serde1"] }
tt = { path = "../tt", version = "0.0.0", default-features = false }
stdx.workspace = true
# span = {workspace = true, default-features = false} does not work
span = { path = "../span", version = "0.0.0", default-features = false }

ra-ap-rustc_lexer.workspace = true

intern.workspace = true
postcard.workspace = true
semver.workspace = true
rayon.workspace = true

[dev-dependencies]
# Enable both features for test.
proc-macro-api = { path = "../proc-macro-api", features = [
    "in-ra",
    "in-proc-macro-srv",
] }

[features]
default = ["in-ra"]
in-rust-tree = ["tt/in-rust-tree"]
in-ra = ["tt/in-ra"]
in-proc-macro-srv = []

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true

[package.metadata.cargo-machete]
ignored = ["ra-ap-rustc_lexer"]
